trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
    - script: donet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'